#*******************************************************************************
# Copyright (c) 2019 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c20,c15
    openshift.io/sa.scc.supplemental-groups: 9112/1 # nexus
    openshift.io/sa.scc.uid-range: 11895/1 # service.nexus
  name: repo-eclipse-org
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: repo-eclipse-org
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  serviceName: nexus
  template:
    metadata:
      labels:
        app: nexus
      name: nexus
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nexus
        image: eclipsecbi/nexus:2.14.16-01
        imagePullPolicy: Always
        securityContext: 
          supplementalGroups: [9112]
        livenessProbe:
          exec:
            command:
              - /bin/bash 
              - -c 
              - "test \"$(curl -s -H 'Accept: application/json' http://localhost:8081/service/local/status | jq -r '.data.state')\" == 'STARTED'"
          periodSeconds: 30
          timeoutSeconds: 60
          initialDelaySeconds: 480
        readinessProbe:
          httpGet:
            path: /service/local/status
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 30
          initialDelaySeconds: 5
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          requests:
            cpu: 2
          limits:
            cpu: 4
            memory: 8Gi
        volumeMounts:
        - mountPath: /var/nexus/work
          name: nexus-work
        - mountPath: /tmp/nexus
          name: nexus-tmp
        env:
          - name: JAVA_OPTS
              # -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle are set in parent image via JAVA_TOOL_OPTIONS
              # sun.zip.disableMemoryMapping=true is necessary until it starts running on jdk9 and latter (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7129299)
            value: >-
              -XshowSettings:vm
              -Dsun.zip.disableMemoryMapping=true
              -Djava.io.tmpdir=/tmp/nexus
              -Dorg.sonatype.nexus.proxy.maven.routing.Config.prefixFileMaxSize=500000
      volumes:
      - name: nexus-work  
        persistentVolumeClaim:
          claimName: nexus-work
      - name: nexus-tmp
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-work
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: repo-eclipse-org
    name: nexus-work
  nfs:
    server: mrslate
    path: /home/data/nexus/nexus-work/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-work
  namespace: repo-eclipse-org
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: repo-eclipse-org
  name: nexus
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: repo-eclipse-org
  annotations:
    haproxy.router.openshift.io/timeout: 60s
  name: nexus
spec:
  host: repo.eclipse.org
  path: /
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: "Service"
    name: "nexus"
    weight: 100
